// UI, progress and parent-review logic.
const TASKS = window.TASKS || [];
const KEY='misha-fp-v3', OLDKEY='misha-fp-v2'; let week=1;
const N={"IED":"Электрика и домотика","IT":"Телекоммуникации","CA I":"Прикладные науки","CCSI":"Коммуникация и соц. науки","PIACI":"Межмодульный проект"};
let S; try{S=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){S=null}
if(!S){try{let old=JSON.parse(localStorage.getItem(OLDKEY)||'null');S=old?{answers:old.answers||{},reviews:old.reviews||{},activity:old.activity||[],steps:{}}:null}catch(e){}}
S=S||{};
S.answers=S.answers||{}; S.reviews=S.reviews||{}; S.activity=S.activity||[]; S.steps=S.steps||{};
S.practice=S.practice||{}; S.videoNotes=S.videoNotes||{}; S.challenges=S.challenges||{};
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function paras(v){return String(v||'').split(/\n\s*\n/).map(x=>`<p>${esc(x)}</p>`).join('')}
function ans(t){return (S.answers[t.id]||'').trim()} function done(t){return !!ans(t)} function step(t,k){return !!((S.steps[t.id]||{})[k])}
function isRich(t){return Array.isArray(t.practice)||Array.isArray(t.vocab)||!!t.visual||Array.isArray(t.videoQuestions)}
function practiceAnswer(t,q){return (((S.practice[t.id]||{})[q.id])??'')}
function practiceAnswered(t,q){return String(practiceAnswer(t,q)).trim()!==''}
function practiceDone(t){return !Array.isArray(t.practice)||!t.practice.length||t.practice.every(q=>practiceAnswered(t,q))}
function videoAnswer(t,i){return (((S.videoNotes[t.id]||{})[i])??'')}
function videoDone(t){return Array.isArray(t.videoQuestions)&&t.videoQuestions.length?t.videoQuestions.every((q,i)=>String(videoAnswer(t,i)).trim()!==''):step(t,'video')}
function richStages(t){return [step(t,'ru'),step(t,'visual'),step(t,'vocab'),step(t,'es'),videoDone(t),practiceDone(t),done(t)]}
function basicStages(t){return [step(t,'ru'),step(t,'es'),step(t,'video'),done(t)]}
function completion(t){let a=isRich(t)?richStages(t):basicStages(t);return a.filter(Boolean).length/a.length}
function missed(t){return t.week<week&&completion(t)<1} function pct(a,b){return b?Math.round(a/b*100):0}
function score(t){if(!done(t))return null;return ans(t).toLowerCase().includes(String(t.needle||'').toLowerCase())?1:0}
function practiceScore(t){if(!Array.isArray(t.practice))return {ok:0,total:0};let total=0,ok=0;t.practice.forEach(q=>{if(q.type==='mcq'||q.type==='number'){total++;let a=practiceAnswer(t,q);if(q.type==='mcq'&&Number(a)===Number(q.answer))ok++;if(q.type==='number'&&a!==''&&Math.abs(Number(a)-Number(q.answer))<1e-9)ok++;}});return{ok,total}}
function stats(){let full=TASKS.filter(t=>completion(t)===1).length,miss=TASKS.filter(missed).length,earned=TASKS.reduce((n,t)=>n+completion(t),0);return{full,miss,total:TASKS.length,progress:pct(earned,TASKS.length)}}
function log(id,what){S.activity.unshift({id,what,at:new Date().toISOString()});S.activity=S.activity.slice(0,160)}
function showView(id,b){['study','progress','parent'].forEach(x=>document.getElementById(x).classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.tab').forEach(x=>x.classList.remove('on'));b.classList.add('on');if(id==='progress')renderProgress();if(id==='parent')renderParent()}
function parentLogin(b){let pin=prompt('PIN родителя (по умолчанию 2468)');let p=localStorage.getItem('misha-parent-pin')||'2468';if(pin===p)showView('parent',b);else alert('Неверный PIN')}
function renderStudy(){let st=stats();document.getElementById('stats').innerHTML=`<div class=stat><span class=muted>Полностью пройдено</span><b>${st.full}/${st.total}</b></div><div class=stat><span class=muted>Общий прогресс</span><b>${st.progress}%</b></div><div class=stat><span class=muted>Текущая неделя</span><b>${week}</b></div><div class=stat><span class=muted>Незакрыто прошлых</span><b>${st.miss}</b></div>`;
document.getElementById('weeks').innerHTML=[1,2,3,4,5,6].map(w=>`<button class="week ${w===week?'on':''}" onclick="week=${w};renderStudy()">${w} неделя</button>`).join('');
let f=document.getElementById('filter').value;document.getElementById('tasks').innerHTML=TASKS.filter(t=>t.week===week&&(!f||t.subject===f)).map(renderTask).join('')}
function renderTask(t){return isRich(t)?renderRichTask(t):renderBasicTask(t)}
function renderPath(t){if(!t.path)return'';return `<div class=pathbox><div><b>Минимум</b><span>${esc(t.path.min)}</span></div><div><b>Нормально</b><span>${esc(t.path.normal)}</span></div><div><b>Глубже</b><span>${esc(t.path.deep)}</span></div></div>`}
function markbox(t,key,label,auto){let checked=auto!==undefined?auto:step(t,key);let dis=auto!==undefined?'disabled':'';return `<label><input type=checkbox ${checked?'checked':''} ${dis} ${auto===undefined?`onchange="mark('${t.id}','${key}',this.checked)"`:''}> ${label}</label>`}
function renderRichTask(t){let c=completion(t), rev=S.reviews[t.id]||{}, ps=practiceScore(t);return `<article class="card task ${c===1?'done':''} ${missed(t)?'missed':''}"><div class=row><div><span class=badge>${esc(t.subject)}</span><span class=badge>${esc(N[t.subject])}</span><h2 style="margin:7px 0 2px">${esc(t.title)}</h2><div class=goal>${esc(t.goal||'')}</div></div><span class="${c===1?'badge good':missed(t)?'badge bad':'badge warn'}">${Math.round(c*100)}%</span></div>
${renderPath(t)}
<div class=checks>${markbox(t,'ru','теория RU')}${markbox(t,'visual','схема')}${markbox(t,'vocab','словарь')}${markbox(t,'es','teoría ES')}${markbox(t,'video','видео',videoDone(t))}${markbox(t,'practice','практика',practiceDone(t))}${markbox(t,'final','итог',done(t))}</div>
<div class=subtabs><button class="subtab on" onclick="subtab(this,'ru-${t.id}')">Объяснение RU</button><button class=subtab onclick="subtab(this,'vis-${t.id}')">Схема</button><button class=subtab onclick="subtab(this,'voc-${t.id}')">Словарь</button><button class=subtab onclick="subtab(this,'es-${t.id}')">Teoría ES</button><button class=subtab onclick="subtab(this,'v-${t.id}')">Видео</button><button class=subtab onclick="subtab(this,'p-${t.id}')">Практика${ps.total?` ${ps.ok}/${ps.total}`:''}</button><button class=subtab onclick="subtab(this,'q-${t.id}')">Итог</button></div>
<div id="ru-${t.id}" class="lesson lesson-${t.id}">${paras(t.theoryRu)}<button class="btn smallbtn" onclick="markAndStay('${t.id}','ru',this)">${step(t,'ru')?'✓ Прочитано':'Отметить: прочитано'}</button></div>
<div id="vis-${t.id}" class="lesson lesson-${t.id} hidden">${renderVisual(t)}<button class="btn smallbtn" onclick="markAndStay('${t.id}','visual',this)">${step(t,'visual')?'✓ Схема понятна':'Отметить: схема понятна'}</button></div>
<div id="voc-${t.id}" class="lesson lesson-${t.id} hidden">${renderVocab(t)}<button class="btn smallbtn" onclick="toggleTranslations(this)">Скрыть / показать перевод</button> <button class="btn smallbtn" onclick="markAndStay('${t.id}','vocab',this)">${step(t,'vocab')?'✓ Словарь пройден':'Отметить: словарь пройден'}</button></div>
<div id="es-${t.id}" class="lesson lesson-${t.id} hidden"><div class=langlabel>ES</div>${paras(t.theoryEs)}<div class="tip small">Попробуй сначала прочитать без словаря. Затем сравни с русской версией и найди ключевые слова.</div><button class="btn smallbtn" onclick="markAndStay('${t.id}','es',this)">${step(t,'es')?'✓ Прочитано по-испански':'Отметить: прочитано по-испански'}</button></div>
<div id="v-${t.id}" class="lesson lesson-${t.id} hidden">${renderVideo(t)}</div>
<div id="p-${t.id}" class="lesson lesson-${t.id} hidden"><h3>Тренировка</h3><div class=muted>Ошибаться здесь нормально: задача — понять причину правильного ответа.</div>${renderPractice(t)}</div>
<div id="q-${t.id}" class="lesson lesson-${t.id} hidden"><h3>Итоговая проверка понимания</h3><p>${esc(t.question)}</p><textarea oninput="answer('${t.id}',this.value)" placeholder="Ответ Миши…">${esc(ans(t))}</textarea>${done(t)?(score(t)?'<span class="badge good">ключевая идея есть</span>':'<span class="badge warn">сохранено · ждёт проверки</span>'):''}${rev.comment?`<p class=parentcomment><b>Комментарий родителя:</b> ${esc(rev.comment)}</p>`:''}${t.challenge?`<div class=challenge><h3>⭐ Хочу разобраться глубже</h3><p>${esc(t.challenge)}</p><textarea oninput="challengeAnswer('${t.id}',this.value)" placeholder="Необязательный ответ…">${esc(S.challenges[t.id]||'')}</textarea></div>`:''}</div></article>`}
function renderBasicTask(t){let c=completion(t), rev=S.reviews[t.id]||{};return `<article class="card task ${c===1?'done':''} ${missed(t)?'missed':''}"><div class=row><div><span class=badge>${esc(t.subject)}</span><span class=badge>${esc(N[t.subject])}</span><h2 style="margin:7px 0 2px">${esc(t.title)}</h2></div><span class="${c===1?'badge good':missed(t)?'badge bad':'badge warn'}">${Math.round(c*100)}%</span></div>
<div class=checks>${markbox(t,'ru','теория RU')}${markbox(t,'es','teoría ES')}${markbox(t,'video','видео')}${markbox(t,'final','ответ',done(t))}</div>
<div class=subtabs><button class="subtab on" onclick="subtab(this,'ru-${t.id}')">Теория RU</button><button class=subtab onclick="subtab(this,'es-${t.id}')">Teoría ES</button><button class=subtab onclick="subtab(this,'v-${t.id}')">Видео</button><button class=subtab onclick="subtab(this,'q-${t.id}')">Проверка</button></div>
<div id="ru-${t.id}" class="lesson lesson-${t.id}">${paras(t.theoryRu)}<b>Термины:</b><div class=vocab>${String(t.learn||'').split(',').map(x=>`<span class=term>${esc(x.trim())}</span>`).join('')}</div></div>
<div id="es-${t.id}" class="lesson lesson-${t.id} hidden">${paras(t.theoryEs)}</div>
<div id="v-${t.id}" class="lesson lesson-${t.id} hidden"><div class=video><div class=play>▶️</div><div><b>${esc(t.videoTitle)}</b><div class=muted>${esc(t.videoNote)}</div><p><a href="${esc(t.videoUrl)}" target=_blank rel=noopener onclick="videoOpen('${t.id}')">Открыть видео / подборку</a></p><label><input type=checkbox ${step(t,'video')?'checked':''} onchange="mark('${t.id}','video',this.checked)"> посмотрел и понял основную мысль</label></div></div></div>
<div id="q-${t.id}" class="lesson lesson-${t.id} hidden"><b>Проверка понимания</b><p>${esc(t.question)}</p><textarea oninput="answer('${t.id}',this.value)" placeholder="Ответ Миши…">${esc(ans(t))}</textarea>${done(t)?(score(t)?'<span class="badge good">ключевая идея есть</span>':'<span class="badge warn">сохранено · ждёт проверки</span>'):''}${rev.comment?`<p><b>Комментарий родителя:</b> ${esc(rev.comment)}</p>`:''}</div></article>`}
function renderVisual(t){if(!t.visual)return'<div class=muted>Схема для этой темы пока не добавлена.</div>';let v=t.visual;if(v.kind==='flow'){return `<h3>${esc(v.title||'Схема')}</h3><div class=diagram-flow>${(v.nodes||[]).map((x,i)=>`<div class=flowwrap><div class=flownode>${esc(x)}</div>${i<(v.nodes||[]).length-1?'<div class=flowarrow>→</div>':''}</div>`).join('')}</div>${v.note?`<div class=diagram-note>${esc(v.note)}</div>`:''}`}return `<h3>${esc(v.title||'Схема')}</h3>`}
function renderVocab(t){let a=t.vocab||[];return `<h3>Ключевые слова</h3><div class=vocabgrid>${a.map(x=>`<div class=vocabcard><b lang=es>${esc(x.es)}</b><span class=translation>${esc(x.ru)}</span>${x.example?`<small lang=es>${esc(x.example)}</small>`:''}</div>`).join('')}</div><div class="tip small">При втором проходе спрячь русский перевод и попробуй вспомнить его сам.</div>`}
function renderVideo(t){if(!t.videoUrl)return'<div class=muted>Видео пока не подобрано.</div>';let q=t.videoQuestions||[];return `<div class=video><div class=play>▶️</div><div><h3>${esc(t.videoTitle)}</h3><div class=muted>${esc(t.videoNote)}</div><p><a href="${esc(t.videoUrl)}" target=_blank rel=noopener onclick="videoOpen('${t.id}')">Открыть видео ↗</a></p></div></div>${q.length?`<h3>После просмотра</h3><div class=muted>Видео считается пройденным, когда сохранены короткие ответы на вопросы.</div>${q.map((x,i)=>`<div class=videoq><label>${i+1}. ${esc(x)}</label><textarea oninput="videoNote('${t.id}',${i},this.value)" placeholder="1–3 предложения…">${esc(videoAnswer(t,i))}</textarea></div>`).join('')}`:`<label><input type=checkbox ${step(t,'video')?'checked':''} onchange="mark('${t.id}','video',this.checked)"> посмотрел и могу объяснить основную мысль</label>`}`}
function renderPractice(t){let a=t.practice||[];return a.map((q,i)=>{let val=practiceAnswer(t,q),status=practiceStatus(q,val);let field='';if(q.type==='mcq'){field=`<div class=choices>${q.options.map((o,j)=>`<label class=choice><input type=radio name="${t.id}-${q.id}" value="${j}" ${String(val)===String(j)?'checked':''} onchange="practiceInput('${t.id}','${q.id}',this.value)"> ${esc(o)}</label>`).join('')}</div>`}else if(q.type==='number'){field=`<input class=numberinput type=number step=any value="${esc(val)}" oninput="practiceInput('${t.id}','${q.id}',this.value)">`}else{field=`<textarea oninput="practiceInput('${t.id}','${q.id}',this.value)" placeholder="Ответ…">${esc(val)}</textarea>`}return `<div class=quiz><b>${i+1}. ${esc(q.q)}</b>${field}${status!==null?`<div class="quizstatus ${status?'qok':'qbad'}">${status?'✓ Верно':'Попробуй ещё раз'}${q.feedback?`<span>${esc(q.feedback)}</span>`:''}</div>`:(practiceAnswered(t,q)&&q.type==='text'?'<div class="quizstatus qsave">Сохранено — открытый ответ можно обсудить или проверить.</div>':'')}</div>`}).join('')}
function practiceStatus(q,val){if(String(val).trim()==='')return null;if(q.type==='mcq')return Number(val)===Number(q.answer);if(q.type==='number')return Math.abs(Number(val)-Number(q.answer))<1e-9;return null}
function subtab(btn,id){let card=btn.closest('.task');card.querySelectorAll('.lesson').forEach(x=>x.classList.add('hidden'));card.querySelector('#'+id).classList.remove('hidden');btn.parentElement.querySelectorAll('.subtab').forEach(x=>x.classList.remove('on'));btn.classList.add('on')}
function toggleTranslations(btn){let lesson=btn.closest('.lesson');lesson.classList.toggle('hideTranslations')}
function mark(id,k,v){S.steps[id]=S.steps[id]||{};S.steps[id][k]=v;log(id,k+(v?' done':' undone'));save();renderStudy()}
function markAndStay(id,k,btn){S.steps[id]=S.steps[id]||{};S.steps[id][k]=true;log(id,k+' done');save();btn.textContent='✓ Готово';btn.classList.add('donebtn')}
function videoOpen(id){log(id,'video opened');save()}
function videoNote(id,i,v){S.videoNotes[id]=S.videoNotes[id]||{};S.videoNotes[id][i]=v;log(id,'video reflection');save()}
function practiceInput(id,qid,v){S.practice[id]=S.practice[id]||{};S.practice[id][qid]=v;log(id,'practice');save()}
function answer(id,v){S.answers[id]=v;log(id,'final answer');save()}
function challengeAnswer(id,v){S.challenges[id]=v;log(id,'challenge');save()}
function renderProgress(){let st=stats();document.getElementById('pstats').innerHTML=`<div class=stat><span class=muted>Полностью</span><b>${st.full}/${st.total}</b></div><div class=stat><span class=muted>Общий прогресс</span><b>${st.progress}%</b></div><div class=stat><span class=muted>Незакрыто</span><b>${st.miss}</b></div><div class=stat><span class=muted>Ответов</span><b>${TASKS.filter(done).length}</b></div>`;
document.getElementById('bars').innerHTML=Object.keys(N).map(s=>{let a=TASKS.filter(t=>t.subject===s),v=a.reduce((n,t)=>n+completion(t),0);return `<p><b>${esc(s)} · ${esc(N[s])}</b> — ${Math.round(v*10)/10} / ${a.length}</p><div class=progress><i style="width:${pct(v,a.length)}%"></i></div>`}).join('');
document.getElementById('activity').innerHTML=S.activity.length?`<table><tr><th>Когда</th><th>Активность</th></tr>${S.activity.slice(0,20).map(x=>{let t=TASKS.find(z=>z.id===x.id);return `<tr><td>${new Date(x.at).toLocaleString('ru-RU')}</td><td>${t?esc(t.subject+' · '+t.title):''} — ${esc(x.what)}</td></tr>`}).join('')}</table>`:'<span class=muted>Пока нет активности.</span>'}
function renderParent(){let st=stats();document.getElementById('parstats').innerHTML=`<div class=stat><span class=muted>Полностью</span><b>${st.full}/${st.total}</b></div><div class=stat><span class=muted>Прогресс</span><b>${st.progress}%</b></div><div class=stat><span class=muted>Незакрыто прошлых</span><b>${st.miss}</b></div><div class=stat><span class=muted>Ответов</span><b>${TASKS.filter(done).length}</b></div>`;
document.getElementById('matrix').innerHTML=`<div class=tablewrap><table><tr><th>Нед.</th><th>Предмет</th><th>Тема</th><th>RU</th><th>Схема</th><th>Словарь</th><th>ES</th><th>Видео</th><th>Практика</th><th>Итог</th><th>%</th></tr>${TASKS.map(t=>`<tr><td>${t.week}</td><td>${esc(t.subject)}</td><td>${esc(t.title)}</td><td>${step(t,'ru')?'✓':'—'}</td><td>${isRich(t)?(step(t,'visual')?'✓':'—'):'·'}</td><td>${isRich(t)?(step(t,'vocab')?'✓':'—'):'·'}</td><td>${step(t,'es')?'✓':'—'}</td><td>${videoDone(t)?'✓':'—'}</td><td>${isRich(t)?(practiceDone(t)?'✓':'—'):'·'}</td><td>${done(t)?'✓':'—'}</td><td>${Math.round(completion(t)*100)}</td></tr>`).join('')}</table></div>`;
let a=TASKS.filter(t=>done(t)||((t.practice||[]).some(q=>practiceAnswered(t,q)))||((t.videoQuestions||[]).some((q,i)=>String(videoAnswer(t,i)).trim())));document.getElementById('reviews').innerHTML=a.length?a.map(t=>renderParentCard(t)).join(''):'<span class=muted>Ответов пока нет.</span>'}
function renderParentCard(t){let r=S.reviews[t.id]||{},ps=practiceScore(t);let practice=(t.practice||[]).map((q,i)=>practiceAnswered(t,q)?`<li><b>${esc(q.q)}</b><br>${esc(practiceAnswer(t,q))}</li>`:'').join('');let vn=(t.videoQuestions||[]).map((q,i)=>String(videoAnswer(t,i)).trim()?`<li><b>${esc(q)}</b><br>${esc(videoAnswer(t,i))}</li>`:'').join('');return `<div class=card><span class=badge>${esc(t.subject)}</span><b>${esc(t.title)}</b>${ps.total?`<span class="badge ${ps.ok===ps.total?'good':'warn'}">авто-практика ${ps.ok}/${ps.total}</span>`:''}${vn?`<details><summary>Ответы после видео</summary><ol>${vn}</ol></details>`:''}${practice?`<details><summary>Тренировочные ответы</summary><ol>${practice}</ol></details>`:''}${done(t)?`<p><b>Итоговый вопрос:</b> ${esc(t.question)}</p><div class=lesson>${esc(ans(t)).replace(/\n/g,'<br>')}</div>`:''}${S.challenges[t.id]?`<details><summary>Дополнительное задание</summary><p>${esc(S.challenges[t.id]).replace(/\n/g,'<br>')}</p></details>`:''}<div class=reviewbox><label>Оценка итогового понимания: <select id="sc-${t.id}"><option value="">—</option><option value=0 ${r.score===0?'selected':''}>0 — переделать</option><option value=1 ${r.score===1?'selected':''}>1 — частично</option><option value=2 ${r.score===2?'selected':''}>2 — хорошо</option></select></label><textarea id="co-${t.id}" placeholder="Комментарий">${esc(r.comment||'')}</textarea><button class="btn primary" onclick="review('${t.id}')">Сохранить проверку</button></div></div>`}
function review(id){let s=document.getElementById('sc-'+id).value;if(s==='')return alert('Поставьте оценку 0–2');S.reviews[id]={score:+s,comment:document.getElementById('co-'+id).value,at:new Date().toISOString()};save();renderParent()}
function exportData(){let b=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='misha-progress-v3.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{S=JSON.parse(r.result);S.answers=S.answers||{};S.reviews=S.reviews||{};S.activity=S.activity||[];S.steps=S.steps||{};S.practice=S.practice||{};S.videoNotes=S.videoNotes||{};S.challenges=S.challenges||{};save();renderStudy();alert('Импортировано')}catch{alert('Неверный файл')}};r.readAsText(f)}
renderStudy();
