// UI, progress and parent-review logic.
const TASKS = window.TASKS || [];
const KEY='misha-fp-v3', OLDKEY='misha-fp-v2'; let week=1;
const N={"IED":"Электрика и домотика","IT":"Телекоммуникации","CA I":"Прикладные науки","CCSI":"Коммуникация и соц. науки","PIACI":"Межмодульный проект"};
let S; try{S=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){S=null}
if(!S){try{let old=JSON.parse(localStorage.getItem(OLDKEY)||'null');S=old?{answers:old.answers||{},reviews:old.reviews||{},activity:old.activity||[],steps:{}}:null}catch(e){}}
S=S||{answers:{},reviews:{},activity:[],steps:{}}; S.steps=S.steps||{}; S.answers=S.answers||{}; S.reviews=S.reviews||{}; S.activity=S.activity||[];
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function ans(t){return (S.answers[t.id]||'').trim()} function done(t){return !!ans(t)} function step(t,k){return !!((S.steps[t.id]||{})[k])}
function completion(t){return [step(t,'ru'),step(t,'es'),step(t,'video'),done(t)].filter(Boolean).length/4} function missed(t){return t.week<week&&completion(t)<1} function pct(a,b){return b?Math.round(a/b*100):0}
function score(t){if(!done(t))return null;return ans(t).toLowerCase().includes(String(t.needle).toLowerCase())?1:0}
function stats(){let full=TASKS.filter(t=>completion(t)===1).length, miss=TASKS.filter(missed).length, steps=TASKS.reduce((n,t)=>n+[step(t,'ru'),step(t,'es'),step(t,'video'),done(t)].filter(Boolean).length,0);return{full,miss,total:TASKS.length,progress:pct(steps,TASKS.length*4)}}
function log(id,what){S.activity.unshift({id,what,at:new Date().toISOString()});S.activity=S.activity.slice(0,120)}
function showView(id,b){['study','progress','parent'].forEach(x=>document.getElementById(x).classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.tab').forEach(x=>x.classList.remove('on'));b.classList.add('on');if(id==='progress')renderProgress();if(id==='parent')renderParent()}
function parentLogin(b){let pin=prompt('PIN родителя (по умолчанию 2468)');let p=localStorage.getItem('misha-parent-pin')||'2468';if(pin===p)showView('parent',b);else alert('Неверный PIN')}
function renderStudy(){let st=stats();document.getElementById('stats').innerHTML=`<div class=stat><span class=muted>Полностью пройдено</span><b>${st.full}/${st.total}</b></div><div class=stat><span class=muted>Общий прогресс</span><b>${st.progress}%</b></div><div class=stat><span class=muted>Текущая неделя</span><b>${week}</b></div><div class=stat><span class=muted>Незакрыто прошлых</span><b>${st.miss}</b></div>`;
document.getElementById('weeks').innerHTML=[1,2,3,4,5,6].map(w=>`<button class="week ${w===week?'on':''}" onclick="week=${w};renderStudy()">${w} неделя</button>`).join('');
let f=document.getElementById('filter').value;document.getElementById('tasks').innerHTML=TASKS.filter(t=>t.week===week&&(!f||t.subject===f)).map(renderTask).join('')}
function renderTask(t){let c=completion(t), rev=S.reviews[t.id]||{};return `<article class="card task ${c===1?'done':''} ${missed(t)?'missed':''}"><div class=row><div><span class=badge>${t.subject}</span><span class=badge>${N[t.subject]}</span><h2 style="margin:7px 0 2px">${t.title}</h2></div><span class="${c===1?'badge good':missed(t)?'badge bad':'badge warn'}">${Math.round(c*100)}%</span></div>
<div class=checks><label><input type=checkbox ${step(t,'ru')?'checked':''} onchange="mark('${t.id}','ru',this.checked)"> теория RU</label><label><input type=checkbox ${step(t,'es')?'checked':''} onchange="mark('${t.id}','es',this.checked)"> teoría ES</label><label><input type=checkbox ${step(t,'video')?'checked':''} onchange="mark('${t.id}','video',this.checked)"> видео</label><label><input type=checkbox ${done(t)?'checked':''} disabled> ответ</label></div>
<div class=subtabs><button class="subtab on" onclick="subtab(this,'ru-${t.id}')">Теория RU</button><button class=subtab onclick="subtab(this,'es-${t.id}')">Teoría ES</button><button class=subtab onclick="subtab(this,'v-${t.id}')">Видео</button><button class=subtab onclick="subtab(this,'q-${t.id}')">Проверка</button></div>
<div id="ru-${t.id}" class="lesson lesson-${t.id}"><p>${t.theoryRu}</p><b>Термины:</b><div class=vocab>${t.learn.split(',').map(x=>`<span class=term>${x.trim()}</span>`).join('')}</div></div>
<div id="es-${t.id}" class="lesson lesson-${t.id} hidden"><p lang=es>${t.theoryEs}</p><div class="muted small">После русского варианта прочитай испанский и найди знакомые технические слова.</div></div>
<div id="v-${t.id}" class="lesson lesson-${t.id} hidden"><div class=video><div class=play>▶️</div><div><b>${t.videoTitle}</b><div class=muted>${t.videoNote}</div><p><a href="${t.videoUrl}" target=_blank rel=noopener onclick="videoOpen('${t.id}')">Открыть видео / подборку</a></p><div class="small muted">Отмечай «видео» только если после просмотра можешь назвать 2–3 новых вещи.</div></div></div></div>
<div id="q-${t.id}" class="lesson lesson-${t.id} hidden"><b>Проверка понимания</b><p>${t.question}</p><textarea oninput="answer('${t.id}',this.value)" placeholder="Ответ Миши…">${ans(t)}</textarea>${done(t)?(score(t)?'<span class="badge good">ключевая идея есть</span>':'<span class="badge warn">сохранено · ждёт проверки</span>'):''}${rev.comment?`<p><b>Комментарий родителя:</b> ${rev.comment}</p>`:''}</div></article>`}
function subtab(btn,id){let card=btn.closest('.task');card.querySelectorAll('.lesson').forEach(x=>x.classList.add('hidden'));card.querySelector('#'+id).classList.remove('hidden');btn.parentElement.querySelectorAll('.subtab').forEach(x=>x.classList.remove('on'));btn.classList.add('on')}
function mark(id,k,v){S.steps[id]=S.steps[id]||{};S.steps[id][k]=v;log(id,k+(v?' done':' undone'));save();renderStudy()}
function videoOpen(id){log(id,'video opened');save()}
function answer(id,v){S.answers[id]=v;log(id,'answer');save()}
function renderProgress(){let st=stats();document.getElementById('pstats').innerHTML=`<div class=stat><span class=muted>Полностью</span><b>${st.full}/${st.total}</b></div><div class=stat><span class=muted>Общий прогресс</span><b>${st.progress}%</b></div><div class=stat><span class=muted>Незакрыто</span><b>${st.miss}</b></div><div class=stat><span class=muted>Ответов</span><b>${TASKS.filter(done).length}</b></div>`;
document.getElementById('bars').innerHTML=Object.keys(N).map(s=>{let a=TASKS.filter(t=>t.subject===s),v=a.reduce((n,t)=>n+completion(t),0);return `<p><b>${s} · ${N[s]}</b> — ${Math.round(v*10)/10} / ${a.length}</p><div class=progress><i style="width:${pct(v,a.length)}%"></i></div>`}).join('');
document.getElementById('activity').innerHTML=S.activity.length?`<table><tr><th>Когда</th><th>Активность</th></tr>${S.activity.slice(0,15).map(x=>{let t=TASKS.find(z=>z.id===x.id);return `<tr><td>${new Date(x.at).toLocaleString('ru-RU')}</td><td>${t?t.subject+' · '+t.title:''} — ${x.what}</td></tr>`}).join('')}</table>`:'<span class=muted>Пока нет активности.</span>'}
function renderParent(){let st=stats();document.getElementById('parstats').innerHTML=`<div class=stat><span class=muted>Полностью</span><b>${st.full}/${st.total}</b></div><div class=stat><span class=muted>Прогресс</span><b>${st.progress}%</b></div><div class=stat><span class=muted>Незакрыто прошлых</span><b>${st.miss}</b></div><div class=stat><span class=muted>Ответов</span><b>${TASKS.filter(done).length}</b></div>`;
document.getElementById('matrix').innerHTML=`<table><tr><th>Нед.</th><th>Предмет</th><th>Тема</th><th>RU</th><th>ES</th><th>Видео</th><th>Ответ</th><th>%</th></tr>${TASKS.map(t=>`<tr><td>${t.week}</td><td>${t.subject}</td><td>${t.title}</td><td>${step(t,'ru')?'✓':'—'}</td><td>${step(t,'es')?'✓':'—'}</td><td>${step(t,'video')?'✓':'—'}</td><td>${done(t)?'✓':'—'}</td><td>${Math.round(completion(t)*100)}</td></tr>`).join('')}</table>`;
let a=TASKS.filter(done);document.getElementById('reviews').innerHTML=a.length?a.map(t=>{let r=S.reviews[t.id]||{};return `<div class=card><span class=badge>${t.subject}</span><b>${t.title}</b><p><b>Вопрос:</b> ${t.question}</p><div class=lesson>${ans(t)}</div><div class=reviewbox><label>Оценка: <select id="sc-${t.id}"><option value="">—</option><option value=0 ${r.score===0?'selected':''}>0 — переделать</option><option value=1 ${r.score===1?'selected':''}>1 — частично</option><option value=2 ${r.score===2?'selected':''}>2 — хорошо</option></select></label><textarea id="co-${t.id}" placeholder="Комментарий">${r.comment||''}</textarea><button class="btn primary" onclick="review('${t.id}')">Сохранить проверку</button></div></div>`}).join(''):'<span class=muted>Ответов пока нет.</span>'}
function review(id){let s=document.getElementById('sc-'+id).value;if(s==='')return alert('Поставьте оценку 0–2');S.reviews[id]={score:+s,comment:document.getElementById('co-'+id).value,at:new Date().toISOString()};save();renderParent()}
function exportData(){let b=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='misha-progress-v3.json';a.click()}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{S=JSON.parse(r.result);S.steps=S.steps||{};save();renderStudy();alert('Импортировано')}catch{alert('Неверный файл')}};r.readAsText(f)}
renderStudy();
